### 엑셀 - load

In [6]:
import pandas as pd

excel = pd.read_excel(
    'data/DMF1.xlsx',
    sheet_name='info',
    engine='openpyxl'
)
type(excel)

pandas.core.frame.DataFrame

In [8]:
menu = pd.read_excel(
    'data/DMF1.xlsx',
    sheet_name='menu',
    engine='openpyxl'
)
menu

,가게이름,거리(분),메뉴,평가
0,홍두깨칼국수,8분,"칼국수, 솥밥정식, 돈까스",칼국수 집인데 솥밥정식이 더 맛있음
1,맘맘테이블,3분,"쌀국수, 분짜",분짜 추천/ 쌀국수도 추천
2,소신이쏘,5분,소갈비찜,크림소갈비찜이 맛있지만 평일 점심에 가면 매운 소갈비찜을 할인된 가격에 판매
3,카라멘야,7분,"카라멘, 본라멘, 마제소바","맵기 단계 설정 가능, 카라멘 추천"
4,고삼이,7분,"고등어구이, 삼치구이, 오징어볶음",고등어구이 추천
5,고래파스타,5분,"새우루꼴라파스타, 봉골레파스타, 트러플버섯크림 파스타",면삶기가 좋음
6,텐동미세기,7분,텐동,합리적인 가격
7,강남불백,2분,"불백, 불낙, 불쭈",4.0/4.5
8,한창희천하일면,5분,"고기국수, 얼큰고기국수, 아부라소바, 매운 아부라소바","기본 고기국수 7000원 맛 가성비 굿. 면 양 조절 가능하고 숙주, 마늘 무료로 ..."

In [9]:
excel = pd.read_excel(
    'data/DMF1.xlsx',
    engine='openpyxl'
)
excel

     이름           전공                   email             github
0   오창희      소프트웨어공학      oche.edu@gmail.com            5chang2
1   강지승  커뮤니케이션미디어학과  kangjiseung1@gmail.com      KANGJISEUNG-1
2   김민수        상담심리학  rlaalstn2568@naver.com         minwater96
3   김수현  커뮤니케이션미디어학과     hisuhy065@gmail.com             suhihy
4   김아영    정보사회미디어학과     irene4618@naver.com            EHYONGI
5   김정아         환경공학   jjungcu0519@gmail.com         jjungcu519
6   김주미        조리과학과      ajsel422@gmail.com           JUMI0110
7   김태주  바이오산업자원공학전공       tj98724@gmail.com              Juin6
8   김현호       경영정보학과  poweremperor@naver.com             gusgh3
9   박진경          행정학    wlsrud0593@naver.com      ParkJinGyeong
10  성찬렬       응용통계학과      s3147078@gmail.com             cksfuf
11  이시운  공연예술학부 무용전공      shiun147@gmail.com            v2k2000
12  이현주          중국학    kangje0610@gmail.com         hyunjuleee
13  이후석          경제학    starpeeker@naver.com  krpythondestroyer
14  조은수       저널리즘전공      joeun115@naver.com          Eunsoojoe
15  최지원        산업보안학  lunatic-ring@naver.com            basquuu
16  최진욱      식량생명공학과      ekdltl30@naver.com      jinwook012345

In [10]:
# 전체 들어가서 dict 로 보는 방법. 앞부분 보기 excel.head 등 (t)참고

### 엑셀 - save

In [14]:
excel = pd.read_excel(
    'data/DMF1.xlsx',
    sheet_name='info',
    engine='openpyxl'
)
student = excel[1:]

In [15]:
# 저장
student.to_excel('data/student.xlsx')

In [18]:
student2 = pd.read_excel(
    'data/student.xlsx',
    sheet_name='Sheet1',
    engine='openpyxl'
)
student2

    Unnamed: 0   이름           전공                   email             github
0            1  강지승  커뮤니케이션미디어학과  kangjiseung1@gmail.com      KANGJISEUNG-1
1            2  김민수        상담심리학  rlaalstn2568@naver.com         minwater96
2            3  김수현  커뮤니케이션미디어학과     hisuhy065@gmail.com             suhihy
3            4  김아영    정보사회미디어학과     irene4618@naver.com            EHYONGI
4            5  김정아         환경공학   jjungcu0519@gmail.com         jjungcu519
5            6  김주미        조리과학과      ajsel422@gmail.com           JUMI0110
6            7  김태주  바이오산업자원공학전공       tj98724@gmail.com              Juin6
7            8  김현호       경영정보학과  poweremperor@naver.com             gusgh3
8            9  박진경          행정학    wlsrud0593@naver.com      ParkJinGyeong
9           10  성찬렬       응용통계학과      s3147078@gmail.com             cksfuf
10          11  이시운  공연예술학부 무용전공      shiun147@gmail.com            v2k2000
11          12  이현주          중국학    kangje0610@gmail.com         hyunjuleee
12          13  이후석          경제학    starpeeker@naver.com  krpythondestroyer
13          14  조은수       저널리즘전공      joeun115@naver.com          Eunsoojoe
14          15  최지원        산업보안학  lunatic-ring@naver.com            basquuu
15          16  최진욱      식량생명공학과      ekdltl30@naver.com      jinwook012345

### CSV-load

In [22]:
file = pd.read_csv('data/DMF1.csv',chunksize=10)
for df in file:
    display(df)

    이름           전공                   email         github
0  오창희      소프트웨어공학      oche.edu@gmail.com        5chang2
1  강지승  커뮤니케이션미디어학과  kangjiseung1@gmail.com  KANGJISEUNG-1
2  김민수        상담심리학  rlaalstn2568@naver.com     minwater96
3  김수현  커뮤니케이션미디어학과     hisuhy065@gmail.com         suhihy
4  김아영    정보사회미디어학과     irene4618@naver.com        EHYONGI
5  김정아         환경공학   jjungcu0519@gmail.com     jjungcu519
6  김주미        조리과학과      ajsel422@gmail.com       JUMI0110
7  김태주  바이오산업자원공학전공       tj98724@gmail.com          Juin6
8  김현호       경영정보학과  poweremperor@naver.com         gusgh3
9  박진경          행정학    wlsrud0593@naver.com  ParkJinGyeong

     이름           전공                   email             github
10  성찬렬       응용통계학과      s3147078@gmail.com             cksfuf
11  이시운  공연예술학부 무용전공      shiun147@gmail.com            v2k2000
12  이현주          중국학    kangje0610@gmail.com         hyunjuleee
13  이후석          경제학    starpeeker@naver.com  krpythondestroyer
14  조은수       저널리즘전공      joeun115@naver.com          Eunsoojoe
15  최지원        산업보안학  lunatic-ring@naver.com            basquuu
16  최진욱      식량생명공학과      ekdltl30@naver.com      jinwook012345

In [20]:
df = pd.read_csv('data/DMF1.csv')
df

     이름           전공                   email             github
0   오창희      소프트웨어공학      oche.edu@gmail.com            5chang2
1   강지승  커뮤니케이션미디어학과  kangjiseung1@gmail.com      KANGJISEUNG-1
2   김민수        상담심리학  rlaalstn2568@naver.com         minwater96
3   김수현  커뮤니케이션미디어학과     hisuhy065@gmail.com             suhihy
4   김아영    정보사회미디어학과     irene4618@naver.com            EHYONGI
5   김정아         환경공학   jjungcu0519@gmail.com         jjungcu519
6   김주미        조리과학과      ajsel422@gmail.com           JUMI0110
7   김태주  바이오산업자원공학전공       tj98724@gmail.com              Juin6
8   김현호       경영정보학과  poweremperor@naver.com             gusgh3
9   박진경          행정학    wlsrud0593@naver.com      ParkJinGyeong
10  성찬렬       응용통계학과      s3147078@gmail.com             cksfuf
11  이시운  공연예술학부 무용전공      shiun147@gmail.com            v2k2000
12  이현주          중국학    kangje0610@gmail.com         hyunjuleee
13  이후석          경제학    starpeeker@naver.com  krpythondestroyer
14  조은수       저널리즘전공      joeun115@naver.com          Eunsoojoe
15  최지원        산업보안학  lunatic-ring@naver.com            basquuu
16  최진욱      식량생명공학과      ekdltl30@naver.com      jinwook012345

### CSV - save

In [23]:
df = pd.read_csv('data/dmf1.csv')
student = df[1:]
student.to_csv('data/student.csv')

In [34]:
df = pd.read_csv('data/student.csv')
dfe = df[:][:]
dfe

    Unnamed: 0   이름           전공                   email             github
1            2  김민수        상담심리학  rlaalstn2568@naver.com         minwater96
2            3  김수현  커뮤니케이션미디어학과     hisuhy065@gmail.com             suhihy
3            4  김아영    정보사회미디어학과     irene4618@naver.com            EHYONGI
4            5  김정아         환경공학   jjungcu0519@gmail.com         jjungcu519
5            6  김주미        조리과학과      ajsel422@gmail.com           JUMI0110
6            7  김태주  바이오산업자원공학전공       tj98724@gmail.com              Juin6
7            8  김현호       경영정보학과  poweremperor@naver.com             gusgh3
8            9  박진경          행정학    wlsrud0593@naver.com      ParkJinGyeong
9           10  성찬렬       응용통계학과      s3147078@gmail.com             cksfuf
10          11  이시운  공연예술학부 무용전공      shiun147@gmail.com            v2k2000
11          12  이현주          중국학    kangje0610@gmail.com         hyunjuleee
12          13  이후석          경제학    starpeeker@naver.com  krpythondestroyer
13          14  조은수       저널리즘전공      joeun115@naver.com          Eunsoojoe
14          15  최지원        산업보안학  lunatic-ring@naver.com            basquuu
15          16  최진욱      식량생명공학과      ekdltl30@naver.com      jinwook012345

In [ ]:
# 1열 제하는 방법?
# 이후 3줄쯤 못적은 내용 있음